## 一，常量张量

In [3]:
import numpy as np 
import tensorflow as tf 

i = tf.constant(1) #tf.int32
l = tf.constant(1, dtype=tf.int64) #tf.int64
f = tf.constant(1.23) #tf.float32
d = tf.constant(3.14, dtype=tf.float64) #tf.double == tf.float64
s = tf.constant("hello world") #tf.string
b = tf.constant(True) #tf.bool

In [7]:
print("int32", tf.int32 == np.int32)
print("int64:", tf.int64 == np.int64)
print("float32:", tf.float32 == np.float32)
print("float64:", tf.float64 == np.float64)
print("double & float:", tf.double == np.float64)
print("bool:", tf.bool == np.bool)
print(tf.string == np.unicode) # tf.string类型和np.unicode类型不等价

int32 True
int64: True
float32: True
float64: True
double & float: True
bool: True
False


In [18]:
scalar = tf.constant(True)  #标量，0维张量

print(tf.rank(scalar))
print(np.ndim(scalar))  # tf.rank的作用和numpy的ndim方法相同

tf.Tensor(0, shape=(), dtype=int32)
0


In [19]:
vector = tf.constant([1.0,2.0,3.0,4.0]) #向量，1维张量

print(tf.rank(vector))
print(np.ndim(vector))

tf.Tensor(1, shape=(), dtype=int32)
1


In [20]:
matrix = tf.constant([[1.0,2.0],[3.0,4.0]]) #矩阵, 2维张量

print(tf.rank(matrix))
print(np.ndim(matrix))

tf.Tensor(2, shape=(), dtype=int32)
2


In [21]:
tensor3 = tf.constant([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])  # 3维张量
print(tf.rank(tensor3))
print(np.ndim(tensor3))

tf.Tensor(3, shape=(), dtype=int32)
3


In [22]:
tensor4 = tf.constant([[[[1.0,1.0],[2.0,2.0]],[[3.0,3.0],[4.0,4.0]]],
                        [[[5.0,5.0],[6.0,6.0]],[[7.0,7.0],[8.0,8.0]]]])  # 4维张量
print(tf.rank(tensor4))
print(np.ndim(tensor4))

tf.Tensor(4, shape=(), dtype=int32)
4


In [27]:
h = tf.constant([123,456])
f = tf.cast(h, tf.float32)
h, f

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([123, 456])>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([123., 456.], dtype=float32)>)

In [29]:
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [30]:
u = tf.constant(u'你好 世界')
u.numpy(), u.numpy().decode('utf-8')

(b'\xe4\xbd\xa0\xe5\xa5\xbd \xe4\xb8\x96\xe7\x95\x8c', '你好 世界')

## 二，变量张量

In [32]:
# 常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0,2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0,1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
2474345875944
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
2475786891512


In [34]:
# 变量的值可以改变，可以通过assign, assign_add等方法给变量重新赋值
v = tf.Variable([1.0,2.0])
print(v)
print(id(v))
v.assign_add([1.0,1.0])  # 所有对实例的操作都要用内建的函数完成
print(v)
print(id(v))

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
2474350785928
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
2474350785928
