## 一，创建张量

In [1]:
import numpy as np 
import tensorflow as tf 

In [2]:
a = tf.constant([1, 2, 3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [4]:
b = tf.range(1, 10, 2)
b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [5]:
c = tf.linspace(0.0, 2*3.14, 100)
c

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.06343435, 0.1268687 , 0.19030304, 0.2537374 ,
       0.31717175, 0.38060609, 0.44404042, 0.5074748 , 0.57090914,
       0.6343435 , 0.6977778 , 0.76121217, 0.82464653, 0.88808084,
       0.9515152 , 1.0149496 , 1.0783839 , 1.1418183 , 1.2052526 ,
       1.268687  , 1.3321213 , 1.3955556 , 1.45899   , 1.5224243 ,
       1.5858587 , 1.6492931 , 1.7127274 , 1.7761617 , 1.839596  ,
       1.9030304 , 1.9664648 , 2.0298991 , 2.0933335 , 2.1567678 ,
       2.2202022 , 2.2836366 , 2.347071  , 2.4105053 , 2.4739397 ,
       2.537374  , 2.6008081 , 2.6642425 , 2.7276769 , 2.7911112 ,
       2.8545456 , 2.91798   , 2.9814143 , 3.0448487 , 3.108283  ,
       3.1717174 , 3.2351518 , 3.2985861 , 3.3620205 , 3.4254549 ,
       3.4888892 , 3.5523233 , 3.6157577 , 3.679192  , 3.7426264 ,
       3.8060608 , 3.8694952 , 3.9329295 , 3.9963639 , 4.0597982 ,
       4.1232324 , 4.186667  , 4.250101  , 4.3135357 , 4.37697   ,
       4.44040

In [6]:
d = tf.zeros([3, 3])
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [7]:
a = tf.ones([3, 3])
b = tf.zeros_like(a)
a, b

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [9]:
b = tf.fill([3, 2], 5)
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 5],
       [5, 5],
       [5, 5]])>

In [12]:
tf.random.set_seed(1.0)
a = tf.random.uniform([5, 2], minval=0, maxval=10)
a

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1.6513085, 9.014812 ],
       [6.309742 , 4.345461 ],
       [2.9193902, 6.4250207],
       [9.757854 , 4.350995 ],
       [6.601019 , 6.0489583]], dtype=float32)>

In [14]:
b = tf.random.normal([3, 3], mean=0.0, stddev=1.0)
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4570122 , -0.40686727,  0.7285778 ],
       [-0.8929778 ,  0.31261146,  0.9942925 ],
       [-1.7842623 , -0.52200514,  0.98080045]], dtype=float32)>

In [15]:
c = tf.random.truncated_normal([5, 5], mean=0.0, stddev=1.0)
c

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.6940167 ,  0.11969317, -1.15846   ,  0.17260405,  1.2539327 ],
       [-0.14577776, -0.1679239 ,  0.24254085, -0.7384888 , -0.02195563],
       [ 0.8474926 ,  0.10189996,  0.62825143,  0.5109858 ,  0.6769444 ],
       [ 0.45561507, -0.92899007,  0.7786587 ,  0.38300708, -0.38201523],
       [ 1.6660208 ,  0.9380581 , -0.8005484 ,  1.5743572 ,  1.335031  ]],
      dtype=float32)>

In [18]:
I = tf.eye(3,3)
t = tf.linalg.diag([1, 2, 3])
I, t

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])>)

## 二，索引切片

In [22]:
tf.random.set_seed(3)
t = tf.random.uniform([5,5], minval=0, maxval=10, dtype=tf.int32)
t

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[4, 7, 4, 2, 9],
       [9, 1, 2, 4, 7],
       [7, 2, 7, 4, 0],
       [9, 6, 9, 7, 2],
       [3, 7, 0, 0, 3]])>

In [23]:
t[0]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 7, 4, 2, 9])>

In [24]:
t[-1]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 7, 0, 0, 3])>

In [27]:
t[1,3], t[1][3], t[1,3]==t[1][3]

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

In [30]:
t[1:4], tf.slice(t, [1,0], [3,-1])

(<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
 array([[9, 1, 2, 4, 7],
        [7, 2, 7, 4, 0],
        [9, 6, 9, 7, 2]])>,
 <tf.Tensor: shape=(3, 5), dtype=int32, numpy=
 array([[9, 1, 2, 4, 7],
        [7, 2, 7, 4, 0],
        [9, 6, 9, 7, 2]])>)

In [32]:
t[1:, :4:2]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[9, 2],
       [7, 7],
       [9, 9],
       [3, 0]])>

In [37]:
x = tf.Variable([[1,2],[3,4]])
x[1, :].assign(tf.constant([0, 0]))
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [0, 0]])>

In [39]:
a = tf.random.uniform([3, 3, 3], minval=0, maxval=10, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[2, 2, 6],
        [5, 7, 6],
        [4, 8, 6]],

       [[4, 6, 3],
        [8, 1, 7],
        [3, 1, 3]],

       [[2, 1, 6],
        [3, 1, 8],
        [9, 3, 7]]])>

In [47]:
a[...,0]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 5, 4],
       [4, 8, 3],
       [2, 3, 9]])>

In [48]:
scores = tf.random.uniform([4, 10, 7], minval=0, maxval=100, dtype=tf.int32)
scores

<tf.Tensor: shape=(4, 10, 7), dtype=int32, numpy=
array([[[ 0, 64, 96, 49, 65, 28, 30],
        [16, 99, 74, 99, 26,  5, 39],
        [12, 48,  9, 39, 34, 76, 10],
        [ 1, 94, 28, 93, 93, 87, 64],
        [85, 74, 20, 81, 85, 21,  1],
        [43, 38, 66,  4,  7,  7, 65],
        [71, 89, 27,  0, 93, 38,  9],
        [70, 79, 37, 28, 72, 38, 31],
        [65, 55, 44, 26, 31, 23, 64],
        [88, 59,  9, 25, 64, 66, 92]],

       [[11, 24,  9, 58, 16, 35, 59],
        [46, 46, 87, 65, 38, 62, 36],
        [37, 52, 47, 29,  2, 51, 48],
        [59, 85, 23, 14, 14,  1, 55],
        [19, 78, 32, 64, 68, 69, 50],
        [94,  3, 55, 30,  4, 93, 52],
        [84, 39, 75, 23, 47, 85, 76],
        [74, 95,  6, 40, 49,  9, 54],
        [67, 47, 74, 18, 11, 68,  6],
        [92, 29, 27, 76, 59, 99, 71]],

       [[78, 37, 24, 59, 54,  9, 79],
        [77, 99,  5, 92, 97, 53, 84],
        [25, 26, 89, 20, 74, 22, 75],
        [97, 30, 10, 25, 24, 78, 85],
        [58, 58, 96, 59, 51, 33, 6

In [53]:
p = tf.gather(scores, [0, 5, 9], axis=1)
p

<tf.Tensor: shape=(4, 3, 7), dtype=int32, numpy=
array([[[ 0, 64, 96, 49, 65, 28, 30],
        [43, 38, 66,  4,  7,  7, 65],
        [88, 59,  9, 25, 64, 66, 92]],

       [[11, 24,  9, 58, 16, 35, 59],
        [94,  3, 55, 30,  4, 93, 52],
        [92, 29, 27, 76, 59, 99, 71]],

       [[78, 37, 24, 59, 54,  9, 79],
        [95, 17, 83,  0, 99, 84, 96],
        [48, 67, 96, 84, 60, 23, 82]],

       [[64, 74, 80, 83, 49, 58, 12],
        [82, 71, 32, 36, 49, 39, 28],
        [35, 63, 52, 84, 34, 59, 64]]])>

In [55]:
q = tf.gather(tf.gather(scores, [0, 5, 9], axis=1), [1, 3, 6], axis=2)
q

<tf.Tensor: shape=(4, 3, 3), dtype=int32, numpy=
array([[[64, 49, 30],
        [38,  4, 65],
        [59, 25, 92]],

       [[24, 58, 59],
        [ 3, 30, 52],
        [29, 76, 71]],

       [[37, 59, 79],
        [17,  0, 96],
        [67, 84, 82]],

       [[74, 83, 12],
        [71, 36, 28],
        [63, 84, 64]]])>

In [56]:
s = tf.gather_nd(scores, indices=[[0, 0], [2, 4], [3, 6]])
s

<tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[ 0, 64, 96, 49, 65, 28, 30],
       [58, 58, 96, 59, 51, 33, 64],
       [ 8, 43, 24, 71, 87, 79, 10]])>

In [57]:
p = tf.boolean_mask(scores, [1, 0, 0, 0, 0, 1, 0, 0, 0, 1], axis=1)
p

<tf.Tensor: shape=(4, 3, 7), dtype=int32, numpy=
array([[[ 0, 64, 96, 49, 65, 28, 30],
        [43, 38, 66,  4,  7,  7, 65],
        [88, 59,  9, 25, 64, 66, 92]],

       [[11, 24,  9, 58, 16, 35, 59],
        [94,  3, 55, 30,  4, 93, 52],
        [92, 29, 27, 76, 59, 99, 71]],

       [[78, 37, 24, 59, 54,  9, 79],
        [95, 17, 83,  0, 99, 84, 96],
        [48, 67, 96, 84, 60, 23, 82]],

       [[64, 74, 80, 83, 49, 58, 12],
        [82, 71, 32, 36, 49, 39, 28],
        [35, 63, 52, 84, 34, 59, 64]]])>

In [65]:
s = tf.boolean_mask(
    scores,
    [[True,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,False,False,False,False,False,False],
     [False,False,False,False,True,False,False,False,False,False],
     [False,False,False,False,False,False,True,False,False,False]]
)

s

<tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[ 0, 64, 96, 49, 65, 28, 30],
       [58, 58, 96, 59, 51, 33, 64],
       [ 8, 43, 24, 71, 87, 79, 10]])>

In [62]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]])
bool_c = tf.boolean_mask(c, c<0)
c, c[c>1], bool_c

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[-1,  1, -1],
        [ 2,  2, -2],
        [ 3, -3,  3]])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 2, 3, 3])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -1, -2, -3])>)

In [78]:
c = tf.constant([[-1, 1, -1], [2, 2, -2], [3, -3, 3]], dtype=tf.float32)
d = tf.where(c<0, tf.fill(c.shape, np.nan), c)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [83]:
indices = tf.where(c<0)
indices, tf.scatter_nd([[0,0], [2,1]], [c[0,0], c[2,1]], c.shape)

(<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
 array([[0, 0],
        [0, 2],
        [1, 2],
        [2, 1]], dtype=int64)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-1.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0., -3.,  0.]], dtype=float32)>)

In [84]:
d = c - tf.scatter_nd([[0,0], [2,1]], [c[0,0], c[2,1]], c.shape)
d, tf.gather_nd(c, indices)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.,  1., -1.],
        [ 2.,  2., -2.],
        [ 3.,  0.,  3.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1., -1., -2., -3.], dtype=float32)>)

In [85]:
indices = tf.where(c<0)
tf.scatter_nd(indices, tf.gather_nd(c, indices), c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

### 三，维度变换

In [86]:
a = tf.random.uniform(
    shape=[1,3,3,2],
    minval=0,
    maxval=255,
    dtype=tf.int32
)

a

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[225, 223],
         [ 22, 182],
         [163,   8]],

        [[ 37, 235],
         [ 36, 107],
         [ 63, 204]],

        [[ 76, 177],
         [ 90, 167],
         [ 69,  96]]]])>

In [87]:
s = tf.squeeze(a)
s

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[225, 223],
        [ 22, 182],
        [163,   8]],

       [[ 37, 235],
        [ 36, 107],
        [ 63, 204]],

       [[ 76, 177],
        [ 90, 167],
        [ 69,  96]]])>

In [93]:
d = tf.expand_dims(s, axis=0)
d

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[225, 223],
         [ 22, 182],
         [163,   8]],

        [[ 37, 235],
         [ 36, 107],
         [ 63, 204]],

        [[ 76, 177],
         [ 90, 167],
         [ 69,  96]]]])>

In [104]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

# 转换成 Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


### 四，合并分割

In [116]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a, b, c], axis=0)

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [117]:
tf.concat([a, b, c], axis=1)

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  5.,  6.,  9., 10.],
       [ 3.,  4.,  7.,  8., 11., 12.]], dtype=float32)>

In [118]:
tf.stack([a, b, c])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [119]:
tf.stack([a, b, c], axis=1)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]],

       [[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]], dtype=float32)>

In [121]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

c = tf.concat([a,b,c],axis = 0)
c

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [124]:
tf.split(c, 3, axis=0)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [125]:
tf.split(c, [2, 2, 2], axis=0)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]