## 一，标量运算

In [2]:
import numpy as np
import tensorflow as tf 

In [3]:
a = tf.constant([[1.0, 2], [-3, 4.0]])
b = tf.constant([[5.0, 5], [7.0, 8.0]])
a+b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  7.],
       [ 4., 12.]], dtype=float32)>

In [4]:
a-b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ -4.,  -3.],
       [-10.,  -4.]], dtype=float32)>

In [5]:
a*b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[  5.,  10.],
       [-21.,  32.]], dtype=float32)>

In [6]:
a/b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.2       ,  0.4       ],
       [-0.42857143,  0.5       ]], dtype=float32)>

In [7]:
a**2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [8]:
a**(0.5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>

In [9]:
a%3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-0.,  1.]], dtype=float32)>

In [10]:
a//3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  0.],
       [-1.,  1.]], dtype=float32)>

In [11]:
a>=2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False,  True]])>

In [13]:
(a>=2)&(a<=3)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False]])>

In [14]:
(a>=2)|(a<=3)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [15]:
a==5 #tf.equal(a,5)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [16]:
tf.sqrt(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>

In [17]:
a = tf.constant([1.0,8.0])
b = tf.constant([5.0,6.0])
c = tf.constant([6.0,7.0])
tf.add_n([a,b,c])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>

In [18]:
tf.print(tf.maximum(a,b))

[5 8]


In [19]:
tf.print(tf.minimum(a,b))

[1 6]


In [20]:
x = tf.constant([2.6,-2.7])

tf.print(tf.math.round(x)) #保留整数部分，四舍五入
tf.print(tf.math.floor(x)) #保留整数部分，向下归整
tf.print(tf.math.ceil(x))  #保留整数部分，向上归整

[3 -3]
[2 -3]
[3 -2]


In [28]:
x = tf.constant([0.9, -0.8, 100.0, -20.0, 0.7])
y = tf.clip_by_value(x, clip_value_min=-1, clip_value_max=1)
z = tf.clip_by_norm(x, clip_norm=3)
x, y, z

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([  0.9,  -0.8, 100. , -20. ,   0.7], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.9, -0.8,  1. , -1. ,  0.7], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([ 0.02647321, -0.02353174,  2.9414675 , -0.5882935 ,  0.02059027],
       dtype=float32)>)

## 二，向量运算

In [33]:
a = tf.range(1,10)
tf.reduce_mean(a), tf.reduce_sum(a), tf.reduce_max(a), tf.reduce_min(a), tf.reduce_prod(a)

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=362880>)

In [41]:
b = tf.reshape(a, (3, 3))
tf.reduce_sum(b, axis=1, keepdims=True), tf.reduce_sum(b, axis=0)

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[ 6],
        [15],
        [24]])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 15, 18])>)

In [46]:
#bool类型的reduce
p = tf.constant([True,True,False])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

0
1


In [52]:
tf.foldr(lambda a,b:a+b, tf.range(10))

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [54]:
a = tf.range(1, 10)
tf.math.cumsum(a), tf.math.cumprod(a)

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=
 array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880])>)

In [55]:
#arg最大最小值索引
a = tf.range(1,10)
tf.print(tf.argmax(a))
tf.print(tf.argmin(a))

8
0


In [60]:
#tf.math.top_k可以用于对张量排序
a = tf.constant([1,3,7,5,4,8])

values, indices = tf.math.top_k(a, 3)
values, indices, a

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 7, 5])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 3])>,
 <tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 3, 7, 5, 4, 8])>)

## 三，矩阵运算

In [61]:
#矩阵乘法
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])
a@b  #等价于tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [62]:
#矩阵转置
a = tf.constant([[1,2],[3,4]])
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [66]:
#矩阵逆，必须为tf.float32或tf.double类型
a = tf.constant([[1.0,2],[3,4]],dtype = tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [70]:
#矩阵求trace
a = tf.constant([[1.0,2],[3,4]],dtype = tf.float32)
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [69]:
#矩阵求范数
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.norm(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

In [71]:
#矩阵行列式
a = tf.constant([[1.0,2],[3,4]])
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [72]:
#矩阵特征值
a = tf.constant([[1.0,2],[-5,4]])
tf.linalg.eigvals(a)

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([2.4999995+2.7838817j, 2.5      -2.783882j ], dtype=complex64)>

In [74]:
#矩阵QR分解, 将一个方阵分解为一个正交矩阵q和上三角矩阵r
#QR分解实际上是对矩阵a实施Schmidt正交化得到q

a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]],dtype = tf.float32)
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

[[-0.123091459 0.904533744 0.408248574]
 [-0.492365927 0.301511645 -0.816496432]
 [-0.861640394 -0.301511586 0.408248156]]
[[-8.1240387 -9.60113621 -11.0782337]
 [0 0.904533505 1.80906785]
 [0 0 2.38418579e-07]]
[[0.999999762 1.99999893 2.99999881]
 [3.99999976 5 6]
 [7 7.99999952 8.99999905]]


In [75]:
#矩阵svd分解
#svd分解可以将任意一个矩阵分解为一个正交矩阵u,一个对角阵s和一个正交矩阵v.t()的乘积
#svd常用于矩阵压缩和降维

a  = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]], dtype = tf.float32)
s,u,v = tf.linalg.svd(a)
tf.print(u,"\n")
tf.print(s,"\n")
tf.print(v,"\n")
tf.print(u@tf.linalg.diag(s)@tf.transpose(v))

#利用svd分解可以在TensorFlow中实现主成分分析降维

[[-0.229847908 0.883461416]
 [-0.524744868 0.240781903]
 [-0.819642 -0.401895702]] 

[9.52551937 0.514301538] 

[[-0.619629383 -0.784894526]
 [-0.784894526 0.619629383]] 

[[1.00000036 2.00000262]
 [3.00000024 4.00000143]
 [5.00000048 6.00000143]]


## 四，广播机制

In [76]:
a = tf.constant([1,2,3])
b = tf.constant([[0,0,0],[1,1,1],[2,2,2]])
b + a  #等价于 b + tf.broadcast_to(a,b.shape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [85]:
#计算广播后计算结果的形状，动态形状，Tensor类型参数
c = tf.constant([1,2,3,4])
d = tf.constant([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
tf.broadcast_dynamic_shape(tf.shape(c),tf.shape(d))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

In [86]:
c+d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])>